### ISSUE TITLE
`posix_spawn: Argument list too long` with many input SVGs

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/nanoemoji#110]
compiling a color font with hundreds of SVGs with current nanoemoji v0.3.1 can make ninja fail with `posix_spawn: Argument list too long` error.

PR #109 from @mavit was an attempt at fixing this issue.

However, the solution doesn't seem to reliably work on Mac and Linux. At least, it works on my Mac but doesn't on my Debian Linux (running under ChromeOS terminal).

I proposed a few solutions in my https://github.com/googlefonts/nanoemoji/pull/109#issuecomment-677515427

I don't think I'll be able to look into it this week, as I need to finish perf and then I'm on holidays until 6 September.

**Comment by mavit** [comment]
It works for me on Fedora, too.  The `$(<file)` syntax is supported by Bash and Korn Shell but evidently not by Debian’s `/bin/sh` (which is Dash).  The Ninja manual says that `sh -c` is used, so I guess a quick workaround would be something like `mkdir bin; ln -s /bin/bash bin/sh; env PATH=$(pwd)/bin:$PATH nanoemoji ...`

As you say, having `write_codepoints.py` read the file itself (or from stdin?) would be most portable, if Windows compatibility is a goal.
