### ISSUE TITLE
Silly compiler, be more faster

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/nanoemoji#218]
Build a full emoji font is pretty slow even on a fairly beefy desktop and downright painful on a laptop. For example, ~900s to build a full Noto Emoji COLRv1 font on my desktop and IIRC when I tried on my laptop it overheated and shutdown. This makes a full rebuild cycle for https://github.com/googlefonts/color-fonts pretty tiresome, I think it took 70 minutes on my desktop last time.

I believe there is probably low hanging fruit in algorithms and opportunity to parallelize, particularly write_font and the shape reuse processing. That work should carry value even if eventually rewritten in something like Rust.

Maybe we can try out https://docs.python.org/3/library/profile.html.

**Comment by rsheeter** [comment]
The flag svgs seem to really hurt us for some reason. 

`2505.5s to run nanoemoji --config config/noto_flag-glyf_colr_1.toml`, which is just 261 svgs.

They also contain tons of layers; `g_1f1ef_1f1ea contains > {MAX_LAYER_V1_COUNT} layers (264); merging last layers in PaintComposite tree`.

**Comment by anthrotype** [comment]
I just tried to run the [pyinstrument](https://github.com/joerick/pyinstrument) profiler and interestingly a lot of time seems to be spent in the `_tuple_safe` function in `fontTools.colorLib.builder` (which is a trick to make mutable otTables hashable).
In particular look at the line `102.260 _tuple_safe  fontTools/colorLib/builder.py:441`. The total clock time was about 146 seconds, so IIUC 70% of the time is spent in that function..

```
  _     ._   __/__   _ _  _  _ _/_   Recorded: 11:50:42  Samples:  115349
 /_//_/// /_\ / //_// / //_'/ //     Duration: 146.584   CPU time: 146.469
/   _/                      v3.2.0

Program: nanoemoji.write_font --config config.toml --ignore_reuse_error -v 1 picosvg/regular/emoji_u1f1f7_1f1f8.svg

146.583 <module>  ../../build/<string>:1
└─ 146.583 run_module  runpy.py:200
      [2 frames hidden]  runpy
         146.583 _run_code  runpy.py:64
         └─ 146.583 <module>  nanoemoji/write_font.py:15
            └─ 146.253 run  absl/app.py:270
                  [17 frames hidden]  absl, ctypes
                     146.250 _run_main  absl/app.py:231
                     └─ 146.236 main  nanoemoji/write_font.py:520
                        └─ 146.162 _generate_color_font  nanoemoji/write_font.py:468
                           ├─ 120.331 _make_ttfont  nanoemoji/write_font.py:159
                           │  └─ 120.325 compileTTF  ufo2ft/__init__.py:161
                           │        [978 frames hidden]  ufo2ft, fontTools, abc, _collections_...
                           │           102.260 _tuple_safe  fontTools/colorLib/builder.py:441
                           │           │  79.104 _tuple_safe  fontTools/colorLib/builder.py:441
                           │           │  │  54.105 _tuple_safe  fontTools/colorLib/builder.py:441
                           │           │  │  │  28.575 _tuple_safe  fontTools/colorLib/builder.py:441
                           │           │  │  │  │  16.486 _tuple_safe  fontTools/colorLib/builder.py:441
                           │           │  │  │  │  │  8.063 _tuple_safe  fontTools/colorLib/builder.py:441
                           │           │  │  │  │  │  ├─ 2.374 isinstance  ../../build/<built-in>:0
                           │           │  │  │  │  └─ 2.528 isinstance  ../../build/<built-in>:0
                           │           │  │  │  ├─ 5.966 dict.items  ../../build/<built-in>:0
                           │           │  │  ├─ 10.053 isinstance  ../../build/<built-in>:0
                           │           │  │  └─ 2.705 __instancecheck__  abc.py:96
                           │           │  │     └─ 1.485 _abc_instancecheck  ../../build/<built-in>:0
                           │           │  ├─ 6.100 dict.items  ../../build/<built-in>:0
                           │           │  └─ 4.437 isinstance  ../../build/<built-in>:0
                           │           ├─ 3.379 isinstance  ../../build/<built-in>:0
                           ├─ 17.330 <listcomp>  nanoemoji/write_font.py:474
                           │  └─ 17.330 create  nanoemoji/color_glyph.py:319
                           │     ├─ 8.912 clip_to_viewbox  picosvg/svg.py:606
                           │     │  └─ 8.906 clip_to_viewbox  picosvg/svg.py:606
                           │     │     └─ 8.461 bounding_box  picosvg/svg_types.py:205
                           │     │        └─ 7.353 as_cmd_seq  picosvg/svg_types.py:221
                           │     │           ├─ 1.921 absolute  picosvg/svg_types.py:484
                           │     │           │  └─ 1.915 _rewrite_path  picosvg/svg_types.py:465
                           │     │           │     └─ 1.908 walk  picosvg/svg_types.py:401
                           │     │           ├─ 1.876 explicit_lines  picosvg/svg_types.py:492
                           │     │           │  └─ 1.716 walk  picosvg/svg_types.py:401
                           │     │           ├─ 1.780 expand_shorthand  picosvg/svg_types.py:500
                           │     │           │  └─ 1.770 walk  picosvg/svg_types.py:401
                           │     │           └─ 1.764 arcs_to_cubics  picosvg/svg_types.py:538
                           │     │              └─ 1.758 walk  picosvg/svg_types.py:401
                           │     └─ 8.417 _painted_layers  nanoemoji/color_glyph.py:274
                           │        └─ 8.318 <lambda>  nanoemoji/color_glyph.py:281
                           │           └─ 8.317 _in_glyph_reuse_key  nanoemoji/color_glyph.py:263
                           │              └─ 8.277 normalize  picosvg/svg_reuse.py:119
                           │                 ├─ 3.050 _affine_friendly  picosvg/svg_reuse.py:84
                           │                 └─ 1.623 walk  picosvg/svg_types.py:401
                           └─ 8.501 <lambda>  nanoemoji/write_font.py:92
                              └─ 8.500 _colr_ufo  nanoemoji/write_font.py:399
                                 └─ 8.497 _ufo_colr_layers  nanoemoji/write_font.py:338
                                    └─ 8.435 _create_glyph  nanoemoji/write_font.py:211
                                       ├─ 4.393 draw_svg_path  nanoemoji/svg_path.py:33
                                       │  └─ 3.507 as_cmd_seq  picosvg/svg_types.py:221
                                       └─ 3.908 _next_name  nanoemoji/write_font.py:204
                                          └─ 1.594 __contains__  ufoLib2/objects/font.py:223
                                                [4 frames hidden]  ufoLib2
```

**Comment by anthrotype** [comment]
pyinstrument can only profile python code, so it can't see inside the ninja subprocess. If you pass the parent nanoemoji process to it (e.g. `pyinstrument -m nanoemoji.nanoemoji ...`) then it won't tell you much. You need to give it a python module (e.g. `pyinstrument -m nanoemoji.write_font` which is where most time is spent I reckon).

If you wish to reproduce the above, this is what I did.
From the `color-fonts` repo root:

```sh
$ nanoemoji font-srcs/noto-emoji/third_party/waved-flags/svg/emoji_u1f1f7_1f1f8.svg
$ cd build
$ pyinstrument -m nanoemoji.write_font --config config.toml --ignore_reuse_error -v 1 picosvg/regular/emoji_u1f1f7_1f1f8.svg
```

**Comment by rsheeter** [comment]
I'd be all for having the root nanoemoji have a flag that causes the various nanoemoji.do_something's to run profiled. Bonus points for it being a filter, say a regex for names to launch with instrumentation.

The tuple-safe thing is interesting. I wonder if we recompute it for the same things over and over or if it's just slow.

It also stands out that clip to viewbox is happening in write_font and therefore serially. That could be parallelized and done at the picosvg step (or as a subsequent per-font step). We could just give picosvg a clip flag.

**Comment by anthrotype** [comment]
> The tuple-safe... I wonder if we recompute it for the same things over and over or if it's just slow.

indeed we are! We should instead do it only once per ot.Paint object since we aren't modifying them inside that loop. Maybe using a cache where the key is the id(ot.Paint) and the value is the result of _as_tuple(paint) already computed.

**Comment by rsheeter** [comment]
I'll try that out and see if it helps.

**Comment by rsheeter** [comment]
Ignore the total time to some extent and focus on the distribution of time.

Original:

<img width="851" alt="Screen Shot 2020-12-04 at 12 25 43 PM" src="https://user-images.githubusercontent.com/6466432/101211569-3e807900-362c-11eb-8bee-74fb018dffd1.png">

Cached tuples:

<img width="832" alt="Screen Shot 2020-12-04 at 12 27 48 PM" src="https://user-images.githubusercontent.com/6466432/101211615-4d672b80-362c-11eb-8175-1f1e0c2ba88c.png">

**Comment by rsheeter** [comment]
clip to viewbox would be good to do in parallel, at time of picosvg production.

**Comment by yisibl** [comment]
Are there plans to use rust rewriting?

**Comment by rsheeter** [comment]
> Are there plans to use rust rewriting?

No concrete plans. We've toyed with the notion of Rust https://github.com/googlefonts/picosvg a few times but never quite gone for it.

**Comment by yisibl** [comment]
If you switch to rust, you can use [svgcleaner](https://github.com/RazrFalcon/svgcleaner), I think this will reduce a lot of svg processing work.

**Comment by yisibl** [comment]
In addition, it should be easier to compile into **wasm** using rust, which is very important for JavaScript and Node.js.  The role of the community is enormous.

**Comment by rsheeter** [comment]
This is much improved in latest FontTools. It's still pretty slow if you want to rebuild all of https://github.com/googlefonts/color-fonts but fast enough to close this for now.
