### ISSUE TITLE
Support Paint{Skew,Rotate,Translate}

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/nanoemoji#224]
If a 2x3 is equivalent to a skew, rotate, or translate we should emit the corresponding (smaller) structure.

If the source is expressed that way (e.g. transform=skew or w/e) it should then emit skew/rotate.

This should enable VF with skew/rotate and save some bytes for translate-only cases.

Translate added in https://github.com/googlefonts/colr-gradients-spec/pull/163

**Comment by rsheeter** [comment]
https://github.com/fonttools/fonttools/pull/2129 should be the last bit of core support needed

**Comment by anthrotype** [comment]
released [fonttools 4.18.2](https://github.com/fonttools/fonttools/releases/tag/4.18.2) with PaintTranslate support

**Comment by rsheeter** [comment]
We now emit several different paint variations from https://github.com/googlefonts/nanoemoji/blob/b8e59a5f22c605fbf7d276d173e97c89538a4f1f/src/nanoemoji/paint.py#L724. Although Skew isn't one of them I think the spirit of this issue is resolved.
