### ISSUE TITLE
What is the difference between twemoji-colr when generating COLR v0?

### ISSUE THREAD

**Issue by yisibl** [googlefonts/nanoemoji#232]
https://github.com/mozilla/twemoji-colr

**Comment by rsheeter** [comment]
The toolchain used there is very different. It's more mature (I see releases back to 2016), based on mature well established tools, and presumably the output is stable and production quality. This tool is under active development, aiming to keep up with the nascent COLR v1 spec as it evolves.

Closing, please reopen if I didn't adequately answer the question.

**Comment by yisibl** [comment]
After testing, I found that the COLR v0 font generated by twemoji has a big compatibility problem on the Web. Only Safari can display normally on Mac.

nanoemoji doesn't have this problem, it's great.
