### ISSUE TITLE
Compute bbox correctly for static

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/nanoemoji#238]
Whatever answer https://github.com/googlefonts/colr-gradients-spec/issues/251 lands on we need to compute the bbox correctly.

This may be awkward under variation, esp with `PaintRotate`.

See https://github.com/googlefonts/nanoemoji/blob/master/src/nanoemoji/write_font.py#L260.

**Comment by drott** [comment]
CC @bungeman

**Comment by rsheeter** [comment]
Context for future self: we need to update to account for the DAG; after #252 it should be correct for what nanoemoji actually generates but not for arbitrary graphs.

**Comment by rsheeter** [comment]
I believe the new ClipBox mechanism does this correctly.
