### ISSUE TITLE
Support running on Windows native python

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/nanoemoji#241]
Currently running nanoemoji fails when run under native Windows python, because of the use of bash-ism that aren't supported when ninja is run in a native Windows environment. E.g. the use of `>` redirection operator to write stdout to a file.
The fix for the latter is to avoid those and have explicit --output-file options instead. picosvg also needs similar option.

See: https://github.com/googlefonts/nanoemoji/pull/240

**Comment by anthrotype** [comment]
I haven't tested this because I don't have a windows machine at hand, but I believe that running nanoemoji inside the WSL should work.
Could anybody pls try and let me know? If that works, I can add a note in the README.md suggesting to temporarily use WSL to run nanoemoji on Windows.
/cc @paullinnerund @madig

**Comment by madig** [comment]
I can confirm that running `tox` on WSL2 (Ubuntu 20.04) runs successfully.
