### ISSUE TITLE
How to configure logging verbosity from the command-line

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/nanoemoji#242]
nanoemoji uses absl-py `absl.logging` module https://abseil.io/docs/python/guides/logging

supposedly absl-py supports configuring that with `-v/--verbosity` option, however passing that option doesn't seem to be doing anything for me. I'd like to make it less verbose, only show WARNING and above, as the output is currently quite chatty.

I'm not familiar with the inner workings of absl-py (I even wonder why we even need to use it in the first place, built-in `argparse` and `logging` should do just fine but I guess it's a matter of habit).

Here's what `nanoemoji --helpfull` shows: 

```
$ nanoemoji --helpfull
[...]
absl.logging:
  --[no]alsologtostderr: also log to stderr?
    (default: 'false')
  --log_dir: directory to write logfiles into
    (default: '')
  --logger_levels: Specify log level of loggers. The format is a CSV list of `name:level`. Where `name` is the logger name used with
    `logging.getLogger()`, and `level` is a level name  (INFO, DEBUG, etc). e.g. `myapp.foo:INFO,other.logger:DEBUG`
    (default: '')
  --[no]logtostderr: Should only log to stderr?
    (default: 'false')
  --[no]showprefixforinfo: If False, do not prepend prefix to info messages when it's logged to stderr, --verbosity is set to INFO
    level, and python logging is used.
    (default: 'true')
  --stderrthreshold: log messages at this level, or more severe, to stderr in addition to the logfile.  Possible values are 'debug',
    'info', 'warning', 'error', and 'fatal'.  Obsoletes --alsologtostderr. Using --alsologtostderr cancels the effect of this flag.
    Please also note that this flag is subject to --verbosity and requires logfile not be stderr.
    (default: 'fatal')
  -v,--verbosity: Logging verbosity level. Messages logged at this level or lower will be included. Set to 1 for debug logging. If the
    flag was not set or supplied, the value will be changed from the default of -1 (warning) to 0 (info) after flags are parsed.
    (default: '-1')
    (an integer)
```

**Comment by anthrotype** [comment]
it turns out we were always calling `nanoemoji.write_font` with `-v 1` (i.e. DEBUG logging). I fixed it to pass forward whatever the value of FLAGS.verbosity (as set on the console) was.

**Comment by anthrotype** [comment]
there were several instances of `print()` calls here and there, which were really meant to be `logging.info()`, so I replaced those too:
https://github.com/googlefonts/nanoemoji/commit/871d9f2ce1ed01561e1ec6499c1195d2451b4a85

One can now call nanoemoji with, e.g. `-v -1` and only get WARNING messages logged.

**Comment by yisibl** [comment]
This is a great improvement.
