### ISSUE TITLE
Ability to support multiple color tables

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/nanoemoji#260]
We have use cases where it would be helpful to have multiple color formats, such as COLR and SVG. Consider making this possible.

**Comment by yisibl** [comment]
Do you mean to include both SVG table and COLR table in the same font file?

**Comment by easrng** [comment]
Exactly! I'd love to have COLR and SVG in one font.

**Comment by rsheeter** [comment]
> Do you mean to include both SVG table and COLR table in the same font file?

Yes, with support for the same set of glyphs

**Comment by anthrotype** [comment]
I found an issue in the current implementation of hybrid COLR+SVG font in #359. When we build the SVG table with --color_format=picosvg (or picosvgz) we reshuffle the order of the color glypsh to be able to group them in consecutive ranges for shape reuse. However, we simply assume that the base color glyphs are the end of the TTFont current glyphOrder; but this is not true when we have both a COLR and and an SVG table. For COLR in fact we create additional layer glyphs that follow the block of base color glyphs. For this SVG color glyph reordering not to mess up the names/order of the COLR layer glyphs, we need to be smarter when selecting the block of base color glyphs, reshuffle only the latter, and keep the head and tail of the TTFont glyphOrder unchanged. I'm already working on a PR.
