### ISSUE TITLE
SVG fonts display missing elements in Adobe apps

### ISSUE THREAD

**Issue by mavit** [googlefonts/nanoemoji#264]
I understand that SVG fonts built by nanoemoji don’t work adequately with (some?) Adobe applications (including InDesign, Illustrator and Photoshop) on (at least some version of) macOS.

There is a screenshot at https://github.com/hfg-gmuend/openmoji/pull/260#issuecomment-808252981 which shows missing elements in some characters.

I don’t have a Mac or these apps myself, and I realise that this isn’t a terribly useful bug report, but I thought it was perhaps worth raising anyway.

**Comment by yisibl** [comment]
The test case in this issue(https://github.com/googlefonts/nanoemoji/issues/266) may help to troubleshoot the problem.

**Comment by anthrotype** [comment]
thanks for the report. And thanks @yisibl for suggesting there's a connection with the use of `<use>` elements. Could it be that those can't be used in OT-SVG fonts? 
I don't see `<use>` element among the explicitly supported features for SVG Native in https://github.com/adobe/svg-native-viewer#svg-native

/cc @rsheeter

**Comment by anthrotype** [comment]
If major apps like Safari or Adobe's have issues with `<use>` elements, then we shall rethink that and avoid it. I would first like to understand whether that is explicitly meant to _not_ work, as in the feature was deliberately excluded from the subset of SVG that is allowed in OT-SVG.

**Comment by anthrotype** [comment]
hm, the `<use>` element seems to be supported by Adobe's svg-native-viewer parser, see https://github.com/adobe/svg-native-viewer/blob/5068110fcbfb59ed495f29d90cb710263072e27c/svgnative/src/SVGDocumentImpl.cpp#L319-L335

**Comment by anthrotype** [comment]
hm this looks to me like a Apple/Adobe bug.. Very weird, since `<use>` is very common/useful mechanism for reusing shapes and thus reduce file size.

In the meantime, I suggest you use `--color_format=untouchedsvg` instead of `--color_format=picosvg` so that the source SVG are not modified and they won't contain `<use>` upon compiling to OT-SVG (of course, if they didn't contain <use> in the first place).

**Comment by yisibl** [comment]
It also does not work in AI.
![image](https://user-images.githubusercontent.com/2784308/114196124-a8ff4800-9983-11eb-82b5-c58c09075d15.png)

**Comment by anthrotype** [comment]
I can also reproduce this issue with Adobe Illustrator (v24.1.2) on macOS using the same test font I uploaded in the other linked issue about Safari: 
https://github.com/googlefonts/nanoemoji/issues/266#issuecomment-817975544

![image](https://user-images.githubusercontent.com/6939968/114434390-dda91480-9bba-11eb-8d67-23c130a2b286.png)

So it appears that neither Safari nor Illustrator support `<use>` elements in OT-SVG documents.

It's strange because even the narrowed-down SVG Native spec (at least implicitly) mentions `<use>` among the supported features: see https://svgwg.org/specs/svg-native/#coords where it says

> The transform property is only supported by SVG Native on the following elements: [...] <use> [...]

**Comment by dirkschulze** [comment]
@anthrotype I can not speak for Safari, but Adobe Illustrator does support the SVG `<use>` element in OT-SVG fonts. I haven't looked into the SVG content but either it is an issue in the SVG content itself or in Adobe Illustrator that the `<use>` element doesn't get rendered.

**Comment by anthrotype** [comment]
Thanks for confirming this @dirkschulze.

I can also confirm that declaring xlink namespace and using the qualified `xlink:href` attribute (instead of the SVG2-only `href` without the xlink namespace) fixed the problem in Illustrator (as well as Safari).

![image](https://user-images.githubusercontent.com/6939968/114530359-c4e44180-9c42-11eb-9e0f-6fca4dc37ae4.png)

@yisibl is already working on a patch to fix this

**Comment by anthrotype** [comment]
I'm afraid there are still problems with Adobe Illustrator even after #271 (which did fix Safari).

When we build OT-SVG using `--color_format=picosvg`, we try to find glyphs that share the same shapes and group them under the same svg document inside the `SVG ` table, then refer to them with `<use>`. This reuse mechanism works for Firefox and Safari, but does not work in Illustrator.

I made a test font, it contains only three color glyphs, the following emojis, using sources from [OpenMoji](https://github.com/hfg-gmuend/openmoji) project: 😁😃😄

I attach below the test font itself, a static html that renders the three glyphs with the font, and an Adobe Illustrator file that uses it:
[AI-OTSVG-Test.zip](https://github.com/googlefonts/nanoemoji/files/6312605/AI-OTSVG-Test.zip)

Here's how it appears on my Mac (next to the same string in Apple Color Emoji), notice the missing parts which are exactly those that get reused:

<img src="https://user-images.githubusercontent.com/6939968/114752545-512f5b00-9d4e-11eb-858d-34593174743e.png" height="500"/>

If you dump the font with ttx and extract the embedded svg document, it looks like this (I reformatted it to add indentation and aid readability):

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
    <g id="glyph2" transform="matrix(18.75 0 0 18.75 0 -1075)">
        <path d="M59,36 A23 23 0 1 1 13,36 A23 23 0 1 1 59,36 Z" fill="#FCEA2B" id="glyph2::0"/>
        <path d="M50.595,41.64 A11.555 11.555 0 0 1 49.725,46.13 C37.235,49.16 24.295,46.47 22.235,46 A11.435 11.435 0 0 1 21.405,41.64 H21.515 S36.315,45.23 50.405,41.71 Z" fill="white" id="glyph2::1"/>
        <path d="M49.725,46.13 C47.935,50.4 43.375,53.36 36.035,53.36 C28.625,53.36 24.005,50.33 22.235,46 C24.295,46.47 37.235,49.16 49.725,46.13 Z" fill="white"/>
        <path d="M60,36 Q60,45.941 52.971,52.971 Q45.941,60 36,60 Q26.059,60 19.029,52.971 Q12,45.941 12,36 Q12,26.059 19.029,19.029 Q26.059,12 36,12 Q45.941,12 52.971,19.029 Q60,26.059 60,36 Z M58,36 Q58,26.887 51.556,20.444 Q45.113,14 36,14 Q26.887,14 20.444,20.444 Q14,26.887 14,36 Q14,45.113 20.444,51.556 Q26.887,58 36,58 Q45.113,58 51.556,51.556 Q58,45.113 58,36 Z" fill="black" id="glyph2::3"/>
        <path d="M51.595,41.632 Q51.615,44.167 50.65,46.511 Q50.456,46.982 49.961,47.102 Q36.685,50.322 22.013,46.975 Q21.503,46.859 21.308,46.374 Q20.387,44.093 20.405,41.633 Q20.412,40.64 21.405,40.64 L21.515,40.64 Q21.635,40.64 21.751,40.668 Q25.375,41.547 30.76,41.998 Q41.517,42.9 50.163,40.74 L50.405,41.71 L50.059,40.772 L50.249,40.702 Q51.188,40.356 51.533,41.294 Q51.594,41.458 51.595,41.632 Z M49.595,41.648 L50.595,41.64 L50.941,42.578 L50.751,42.648 Q50.7,42.667 50.647,42.68 Q41.68,44.92 30.593,43.992 Q25.054,43.528 21.279,42.612 L21.515,41.64 L21.515,42.64 L21.405,42.64 L21.405,41.64 L22.405,41.647 Q22.39,43.711 23.162,45.626 L22.235,46 L22.457,45.025 Q36.671,48.268 49.489,45.158 L49.725,46.13 L48.8,45.749 Q49.612,43.779 49.595,41.648 Z" fill="black" id="glyph2::4"/>
        <path d="M50.647,46.517 Q47.359,54.36 36.035,54.36 Q24.572,54.36 21.309,46.378 Q20.931,45.453 21.857,45.074 Q22.149,44.955 22.458,45.025 Q36.671,48.268 49.489,45.158 Q50.461,44.922 50.697,45.894 Q50.774,46.214 50.647,46.517 Z M48.803,45.743 L49.725,46.13 L49.961,47.102 Q36.685,50.322 22.013,46.975 L22.235,46 L23.161,45.622 Q25.915,52.36 36.035,52.36 Q46.029,52.36 48.803,45.743 Z" fill="black" id="glyph2::5"/>
        <path d="M30.78,32.81 Q29.797,30.596 27.375,30.596 Q24.953,30.596 23.97,32.81 Q23.564,33.723 22.65,33.317 Q21.736,32.911 22.142,31.998 Q23.653,28.596 27.375,28.596 Q31.097,28.596 32.608,31.998 Q33.014,32.911 32.1,33.317 Q31.186,33.723 30.78,32.81 Z" fill="black" id="glyph2::6"/>
        <use xlink:href="#glyph2::6" x="17.25"/>
    </g>
    <g id="glyph3" transform="matrix(18.75 0 0 18.75 0 -1075)">
        <use xlink:href="#glyph2::0"/>
        <use xlink:href="#glyph2::1"/>
        <path d="M49.725,46.13 C47.935,50.4 43.375,53.36 36.035,53.36 C28.625,53.36 24.005,50.33 22.235,46 C24.295,46.47 37.235,49.16 49.725,46.13 Z" fill="#EA5A47" id="glyph3::2"/>
        <use xlink:href="#glyph2::3"/>
        <path d="M31.568,30.818 A3 5.404 0 1 1 25.568,30.818 A3 5.404 0 1 1 31.568,30.818 Z" fill="black" id="glyph3::4"/>
        <use xlink:href="#glyph3::4" x="14.864" y="0.004"/>
        <use xlink:href="#glyph2::4"/>
        <use xlink:href="#glyph2::5"/>
    </g>
    <g id="glyph4" transform="matrix(18.75 0 0 18.75 0 -1075)">
        <use xlink:href="#glyph2::0"/>
        <use xlink:href="#glyph2::1"/>
        <use xlink:href="#glyph3::2"/>
        <use xlink:href="#glyph2::3"/>
        <use xlink:href="#glyph2::4"/>
        <use xlink:href="#glyph2::5"/>
        <use xlink:href="#glyph2::6"/>
        <use xlink:href="#glyph2::6" x="17.25"/>
    </g>
</svg>
```

**Comment by anthrotype** [comment]
This is how the same font and string should look like (this is Firefox, Safari is identical as well):

<img width="518" alt="Screenshot 2021-04-14 at 19 28 05" src="https://user-images.githubusercontent.com/6939968/114760757-9441fc00-9d57-11eb-90d8-5698682ff626.png">

**Comment by anthrotype** [comment]
I digged deeper, and I found out that if I move all the elements that are reused by more than one glyph to a `<defs>` element defined at the top, before and outside any of the `<g>` glyph subtrees, then the references work in Adobe Illustrator as well:

<img width="300" alt="Screenshot 2021-04-15 at 16 19 15" src="https://user-images.githubusercontent.com/6939968/114894391-80a19e80-9e06-11eb-9ca5-6fb0be9685cb.png">


[AI-OTSVG-Test-working.zip](https://github.com/googlefonts/nanoemoji/files/6319114/AI-OTSVG-Test-working.zip)

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
    <defs>
        <path d="M30.78,32.81 Q29.797,30.596 27.375,30.596 Q24.953,30.596 23.97,32.81 Q23.564,33.723 22.65,33.317 Q21.736,32.911 22.142,31.998 Q23.653,28.596 27.375,28.596 Q31.097,28.596 32.608,31.998 Q33.014,32.911 32.1,33.317 Q31.186,33.723 30.78,32.81 Z" fill="black" id="glyph2::6"/>
        <path d="M59,36 A23 23 0 1 1 13,36 A23 23 0 1 1 59,36 Z" fill="#FCEA2B" id="glyph2::0"/>
        <path d="M50.595,41.64 A11.555 11.555 0 0 1 49.725,46.13 C37.235,49.16 24.295,46.47 22.235,46 A11.435 11.435 0 0 1 21.405,41.64 H21.515 S36.315,45.23 50.405,41.71 Z" fill="white" id="glyph2::1"/>
        <path d="M60,36 Q60,45.941 52.971,52.971 Q45.941,60 36,60 Q26.059,60 19.029,52.971 Q12,45.941 12,36 Q12,26.059 19.029,19.029 Q26.059,12 36,12 Q45.941,12 52.971,19.029 Q60,26.059 60,36 Z M58,36 Q58,26.887 51.556,20.444 Q45.113,14 36,14 Q26.887,14 20.444,20.444 Q14,26.887 14,36 Q14,45.113 20.444,51.556 Q26.887,58 36,58 Q45.113,58 51.556,51.556 Q58,45.113 58,36 Z" fill="black" id="glyph2::3"/>
        <path d="M51.595,41.632 Q51.615,44.167 50.65,46.511 Q50.456,46.982 49.961,47.102 Q36.685,50.322 22.013,46.975 Q21.503,46.859 21.308,46.374 Q20.387,44.093 20.405,41.633 Q20.412,40.64 21.405,40.64 L21.515,40.64 Q21.635,40.64 21.751,40.668 Q25.375,41.547 30.76,41.998 Q41.517,42.9 50.163,40.74 L50.405,41.71 L50.059,40.772 L50.249,40.702 Q51.188,40.356 51.533,41.294 Q51.594,41.458 51.595,41.632 Z M49.595,41.648 L50.595,41.64 L50.941,42.578 L50.751,42.648 Q50.7,42.667 50.647,42.68 Q41.68,44.92 30.593,43.992 Q25.054,43.528 21.279,42.612 L21.515,41.64 L21.515,42.64 L21.405,42.64 L21.405,41.64 L22.405,41.647 Q22.39,43.711 23.162,45.626 L22.235,46 L22.457,45.025 Q36.671,48.268 49.489,45.158 L49.725,46.13 L48.8,45.749 Q49.612,43.779 49.595,41.648 Z" fill="black" id="glyph2::4"/>
        <path d="M50.647,46.517 Q47.359,54.36 36.035,54.36 Q24.572,54.36 21.309,46.378 Q20.931,45.453 21.857,45.074 Q22.149,44.955 22.458,45.025 Q36.671,48.268 49.489,45.158 Q50.461,44.922 50.697,45.894 Q50.774,46.214 50.647,46.517 Z M48.803,45.743 L49.725,46.13 L49.961,47.102 Q36.685,50.322 22.013,46.975 L22.235,46 L23.161,45.622 Q25.915,52.36 36.035,52.36 Q46.029,52.36 48.803,45.743 Z" fill="black" id="glyph2::5"/>
        <path d="M49.725,46.13 C47.935,50.4 43.375,53.36 36.035,53.36 C28.625,53.36 24.005,50.33 22.235,46 C24.295,46.47 37.235,49.16 49.725,46.13 Z" fill="#EA5A47" id="glyph3::2"/>
        <path d="M31.568,30.818 A3 5.404 0 1 1 25.568,30.818 A3 5.404 0 1 1 31.568,30.818 Z" fill="black" id="glyph3::4"/>
    </defs>
    <g id="glyph2" transform="matrix(18.75 0 0 18.75 0 -1075)">
        <use xlink:href="#glyph2::0"/>
        <use xlink:href="#glyph2::1"/>
        <path d="M49.725,46.13 C47.935,50.4 43.375,53.36 36.035,53.36 C28.625,53.36 24.005,50.33 22.235,46 C24.295,46.47 37.235,49.16 49.725,46.13 Z" fill="white"/>
        <use xlink:href="#glyph2::3"/>
        <use xlink:href="#glyph2::4"/>
        <use xlink:href="#glyph2::5"/>
        <use xlink:href="#glyph2::6"/>
        <use xlink:href="#glyph2::6" x="17.25"/>
    </g>
    <g id="glyph3" transform="matrix(18.75 0 0 18.75 0 -1075)">
        <use xlink:href="#glyph2::0"/>
        <use xlink:href="#glyph2::1"/>
        <use xlink:href="#glyph3::2"/>
        <use xlink:href="#glyph2::3"/>
        <use xlink:href="#glyph3::4"/>
        <use xlink:href="#glyph3::4" x="14.864" y="0.004"/>
        <use xlink:href="#glyph2::4"/>
        <use xlink:href="#glyph2::5"/>
    </g>
    <g id="glyph4" transform="matrix(18.75 0 0 18.75 0 -1075)">
        <use xlink:href="#glyph2::0"/>
        <use xlink:href="#glyph2::1"/>
        <use xlink:href="#glyph3::2"/>
        <use xlink:href="#glyph2::3"/>
        <use xlink:href="#glyph2::4"/>
        <use xlink:href="#glyph2::5"/>
        <use xlink:href="#glyph2::6"/>
        <use xlink:href="#glyph2::6" x="17.25"/>
    </g>
</svg>
```

So what is not supported in Illustrator is a direct reference from one glyph to an inner element of another glyph. If the reused shape is external to both (e.g. defined in a `<defs>` group), then it works.

**Comment by behdad** [comment]
> So what is not supported in Illustrator is a direct reference from one glyph to an inner element of another glyph. If the reused shape is external to both (e.g. defined in a `<defs>` group), then it works.

That sounds like what SVG-Native intended to spec.

**Comment by anthrotype** [comment]
the OT-SVG spec also has an explicit example of using `<defs>` to define shared elements across glyphs:

https://docs.microsoft.com/en-us/typography/opentype/spec/svg#example-4-common-elements-shared-across-glyphs-in-same-svg-doc

Ok, we shall change the code do that if that's the expectation. It's a bit of a pity because it would mean adding an extra `<use>` reference also for the first occurence of a reused shape, instead of only for subsequent ones.
