### ISSUE TITLE
AttributeError: 'SVGCircle' object has no attribute 'd'

### ISSUE THREAD

**Issue by yisibl** [googlefonts/nanoemoji#265]
The svg file:
```html
<svg width="200" height="200" viewBox="0 0 200 200" version="1.1" xmlns="http://www.w3.org/2000/svg">
    <circle fill="#F49924" cx="100" cy="100" r="100" />
</svg>
```

```shell
nanoemoji --color_format=glyf_colr_0
```

**Comment by anthrotype** [comment]
I cannot reproduce, I'm on mac in a fresh virtual environment, using current nanoemoji==0.7.1 and picosvg==0.14.0
what versions have you got?
what's the full error message that you get?

**Comment by yisibl** [comment]
Sorry, it may be a problem with my local environment. I regenerated the virtual environment and it is now okay.
