### ISSUE TITLE
The path with stroke-dasharray is converted incorrectly.

### ISSUE THREAD

**Issue by yisibl** [googlefonts/nanoemoji#275]
```svg
<svg width="170" height="89" viewBox="0 0 170 89" fill="none" xmlns="http://www.w3.org/2000/svg">
	<path d="M2 87L85 4L168 87" stroke="red" stroke-width="5" stroke-dasharray="20 6"/>
</svg>
```

`nanoemoji --color_format=picosvg` or `nanoemoji --color_format=glyf_colr_0` 

```xml
    <svgDoc endGlyphID="2" startGlyphID="2">
      <![CDATA[
<svg xmlns="http://www.w3.org/2000/svg" version="1.1">
    <defs />
    <g id="glyph2" transform="matrix(13.483 0 0 13.483 -0.067 -950)">
        <path d="M2,87 L85,4 L168,87" fill="black" />
        <path d="M0.232,85.232 L14.374,71.09 L17.91,74.626 L3.768,88.768 L0.232,85.232 Z M18.617,66.847 L32.759,52.705 L36.295,56.241 L22.153,70.383 L18.617,66.847 Z M37.002,48.463 L51.144,34.321 L54.679,37.856 L40.537,51.998 L37.002,48.463 Z M55.387,30.078 L69.529,15.936 L73.064,19.471 L58.922,33.613 L55.387,30.078 Z M73.771,11.693 L85,0.464 L91.449,6.913 L87.913,10.449 L83.232,5.768 L85,4 L86.768,5.768 L77.307,15.229 L73.771,11.693 Z M95.692,11.156 L109.834,25.298 L106.298,28.834 L92.156,14.692 L95.692,11.156 Z M114.076,29.541 L128.219,43.683 L124.683,47.219 L110.541,33.076 L114.076,29.541 Z M132.461,47.926 L146.603,62.068 L143.068,65.603 L128.926,51.461 L132.461,47.926 Z M150.846,66.31 L164.988,80.453 L161.453,83.988 L147.31,69.846 L150.846,66.31 Z M169.231,84.695 L169.768,85.232 L166.232,88.768 L165.695,88.231 L169.231,84.695 Z" fill="red" />
    </g>
</svg>
]]>
    </svgDoc>
```

## Actual
![image](https://user-images.githubusercontent.com/2784308/114830824-3bc63980-9dff-11eb-875a-d916dbcb7cef.png)

## Expect
![image](https://user-images.githubusercontent.com/2784308/114831135-9cee0d00-9dff-11eb-9812-27649d5cf072.png)

## Figma

In fact, Figma will optimize the path of the inflection point to make it look evenly divided, so we should add a description in the readme to tell users that when using `stroke-dasharray` to draw graphics, please execute the `Outline stroke` command first. Otherwise, the resulting dashed line will not look the same as in Figma.
![image](https://user-images.githubusercontent.com/2784308/114831284-c9a22480-9dff-11eb-8aed-6c8e29b35b3f.png)

**Comment by anthrotype** [comment]
it's because the `fill="none"` is defined in the root `<svg>` element. Currently we are only handling attribute inheritance for `<g>` elements and their children. If you move the `fill="none"` attribute down to either a `<g>` container or to directly the shape using it, then you should no longer see the default black fill.

We use skia to convert the dash-array to outline paths, so that's what we get back. In fact that's exactly how the original svg with the dash-array would render in Chrome.

**Comment by yisibl** [comment]
So do you consider moving the fill="none" of the svg to the child element?
