### ISSUE TITLE
winding issue when intra-glyph reused shapes overlap

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/nanoemoji#287]
In `nanoemoji.color_glyph._painted_layers`, we group consecutive paths with the same paint and the same "normalized" version (i.e. one that compares == even if offset, scaled, rotated, etc.) in the same `PaintedLayer`, which later on gets encoded as a single `glyf` composite glyph, the reused paths encoded as components of the first one with a given transform.

But when these components overlap with each other and the transform is such that the winding contour direction gets flipped (negative determinant), then we can see glitches such as this:

<img width="400" alt="Screenshot 2021-05-10 at 17 30 17" src="https://user-images.githubusercontent.com/6939968/117692969-72e8fa00-b1b5-11eb-8b63-517bd19aa62e.png">

This is more visible when we zoom in on one of the stars (which in this particular flag are comprised of many triangles overlapping one another):

<img width="99" alt="Screenshot 2021-05-10 at 17 30 29" src="https://user-images.githubusercontent.com/6939968/117692965-72506380-b1b5-11eb-9efd-84a3f18c188e.png">

I think we should avoid the intra-glyph reuse if the components' paths overlap with one another and the transform flips the winding direction.

We can use `picosvg.svg_types.intersection` function to check if any pair of paths that could be reused do overlap (their intersection is not empty), and if they do, we revert to encoding them as distinct PaintedLayers (which will get encoded as distinct contour glyfs)

**Comment by rsheeter** [comment]
I hate winding lol. Great catch.
