### ISSUE TITLE
ufo2ft 2.22.0 breaks us

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/nanoemoji#304]
`ERROR    ufo2ft.outlineCompiler:outlineCompiler.py:1391 'e000' has invalid curve format; skipped`

**Comment by rsheeter** [comment]
@anthrotype don't suppose this rings any bells?

**Comment by rsheeter** [comment]
Presumably due to "outlineCompiler now uses the new fonttools' TTGlyphPointPen" https://github.com/googlefonts/ufo2ft/releases/tag/v2.22.0

**Comment by yisibl** [comment]
After upgrading nanoemoji, it can no longer be displayed in Chrome.
https://at.alicdn.com/t/project/2433183/c895424c-8756-4a7c-9405-9faf1bfff12b.html
![image](https://user-images.githubusercontent.com/2784308/125627287-fadd6885-e1e0-4fb5-b1f2-c769047a5bca.png)

Before: https://at.alicdn.com/t/project/2433183/a666dc8e-60d4-4bea-ab91-3b652da691f8.html

**Comment by rsheeter** [comment]
Is that from head or the latest release?

**Comment by yisibl** [comment]
> Is that from head or the latest release?

nanoemoji v0.9.1，This problem can be solved when ufo2ft is locked to 2.21.0.

It seems that the risks brought by the unlocked version are still great.

**Comment by anthrotype** [comment]
it's actually a bug in fonttools, not in ufo2ft. I'll take a look https://github.com/fonttools/fonttools/issues/2365

**Comment by yisibl** [comment]
alright, got it.

**Comment by anthrotype** [comment]
fixed by https://github.com/googlefonts/nanoemoji/pull/307
