### ISSUE TITLE
ot-svg doesn't support transform paints

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/nanoemoji#323]
In `src/nanoemoji/svg.py` see `# TODO: support transform types`

**Comment by anthrotype** [comment]
I just tried to build a `--color_format picosvg` font using a source file that I know would produce a PaintTransform when built as COLRv1, and it _does_ work.
The reason being `color_glyph._painted_layers` always returns a list of either PaintGlyph or PaintComposite (when there's a group with alpha), never any PaintTransform. The latter are only introduced in the glyph reuse code when a match is found.
So the current code in `nanoemoji/svg.py` following #321 can already handle all the SVG inputs which picosvg and nanoemoji.color_glyph currently produce. The possible PaintTransforms children of the root PaintGlyphs (used for transformed radial gradients) are already handled by the current nanoemoji/svg.py code (as `gradientTransform` attributes)
We should probably consider this TODO only as theoretical right now.

**Comment by rsheeter** [comment]
Closing as there is no intent to do additional work at this time. Simple examples work just fine:

```svg
<svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">
  <rect x="2" y="2" width="6" height="2" fill="purple" />
  <rect x="4" y="4" width="6" height="2" fill="darkgreen" opacity="0.8" transform="rotate(45, 4,2)"/>
</svg>
```

Encodes into the font (color_format=picosvg) as:

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
  <defs>
    <path d="M2,2 L8,2 L8,4 L2,4 L2,2 Z" id="g_270d.0"/>
  </defs>
  <g id="glyph2" transform="matrix(120 0 0 120 37.5 -950)">
    <use xlink:href="#g_270d.0" fill="purple"/>
    <use xlink:href="#g_270d.0" x="2.586" y="0.586" transform="matrix(0.707 0.707 -0.707 0.707 1.172 -1.657)" fill="darkgreen" opacity="0.8"/>
  </g>
</svg>
```
