### ISSUE TITLE
CompositeMode enum lacks PLUS operator

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/nanoemoji#326]
We need to update the CompositeMode enum to add the missing PLUS operator, like https://github.com/fonttools/fonttools/pull/2390

It's not super urgent given that we currently only use SRC_IN (which occurs before the renumbered modes) 

https://github.com/googlefonts/nanoemoji/blob/a2eb92e9d738c3e0574e0574353f7a3269d06d1a/src/nanoemoji/paint.py#L45-L74

**Comment by rsheeter** [comment]
Good catch!
