### ISSUE TITLE
Some Noto Emoji lose gradients

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/nanoemoji#331]
![image (4)](https://user-images.githubusercontent.com/6466432/131915194-25f81b97-f5fd-4bfe-bcda-8a59a7c11450.png)

Pattern seems to be a loss of gradient.

**Comment by drott** [comment]
Original issue for what we then discussed in #332 - closing, proposed fix in https://skia-review.googlesource.com/c/skia/+/445936
