### ISSUE TITLE
Failing diffs for emoji that use compositing

### ISSUE THREAD

**Issue by drott** [googlefonts/nanoemoji#332]
Example, thought bubble 💭

SVG https://paste.googleplex.com/5424305732059136
TTX https://paste.googleplex.com/5834443433443328
Parsed FreeType https://paste.googleplex.com/4596339116605440

![image](https://user-images.githubusercontent.com/1021784/132038496-42d4d948-6ad3-40cf-9595-8349c3f1f966.png)

**Comment by rsheeter** [comment]
SVG https://paste.googleplex.com/5424305732059136
Colorized https://codepen.io/rs42/pen/ExXyzOE?editors=1100

**Comment by rsheeter** [comment]
Composite *may* be a red herring; the parts that's missing is just a simple shape with gradient.

**Comment by rsheeter** [comment]
Theory: if src_in were applied when combining the composited content with the prior layers this would result.

**Comment by rsheeter** [comment]
Demo of same thing with/without composite in https://github.com/rsheeter/nanoemoji_322. I think that suggests the theory above is what's happening?

![image](https://user-images.githubusercontent.com/6466432/132042437-fde927b5-abcd-48b8-89ea-784817d1721c.png)

**Comment by drott** [comment]
Skia fix in https://skia-review.googlesource.com/c/skia/+/445936/
color-fonts test in https://github.com/googlefonts/color-fonts/pull/73
