### ISSUE TITLE
ClipBox too small with transformed reused shape (circus tent emoji example)

### ISSUE THREAD

**Issue by drott** [googlefonts/nanoemoji#335]
Simplifying the circus tent emoji, in the Skia rendering, the second yellow patch of the vertical tent wall goes missing. This path seems to be a mirrored version of the left side left patch of the vertical wall. 

Whether it gets shifted out of the viewport or whether something goes wrong with the color line coordinates, similar to issue #334 needs investigation.

![tent](https://user-images.githubusercontent.com/1021784/132232029-3d393fc3-624a-43a9-a4a1-4c12e3261afa.png)

Simplified SVG

```
<svg enable-background="new 0 0 128 128" viewBox="0 0 128 128"
	xmlns="http://www.w3.org/2000/svg">
	<linearGradient id="g" x1="32.5" x2="32.5" y1="64.167" y2="125.94" gradientUnits="userSpaceOnUse">
		<stop stop-color="#FDD835" offset="0"/>
		<stop stop-color="#F9A825" offset="1"/>
	</linearGradient>
	<path d="m20 64s12 24 8 60h16s4-44-4-60h-20z" fill="url(#g)"/>
	<linearGradient id="f" x1="95.5" x2="95.5" y1="64.167" y2="125.94" gradientUnits="userSpaceOnUse">
		<stop stop-color="#FDD835" offset="0"/>
		<stop stop-color="#F9A825" offset="1"/>
	</linearGradient>
	<path d="m108 64s-12 24-8 60h-16s-4-44 4-60h20z" fill="url(#f)"/>
</svg>
```

COLR

```
 <COLR>
    <Version value="1"/>
    <!-- BaseGlyphRecordCount=0 -->
    <!-- LayerRecordCount=0 -->
    <BaseGlyphList>
      <!-- BaseGlyphCount=1 -->
      <BaseGlyphPaintRecord index="0">
        <BaseGlyph value="u1F3AA"/>
        <Paint Format="1"><!-- PaintColrLayers -->
          <NumLayers value="2"/>
          <FirstLayerIndex value="0"/>
        </Paint>
      </BaseGlyphPaintRecord>
    </BaseGlyphList>
    <LayerList>
      <!-- LayerCount=2 -->
      <Paint index="0" Format="10"><!-- PaintGlyph -->
        <Paint Format="4"><!-- PaintLinearGradient -->
          <ColorLine>
            <Extend value="pad"/>
            <!-- StopCount=2 -->
            <ColorStop index="0">
              <StopOffset value="0.0"/>
              <PaletteIndex value="1"/>
              <Alpha value="1.0"/>
            </ColorStop>
            <ColorStop index="1">
              <StopOffset value="1.0"/>
              <PaletteIndex value="0"/>
              <Alpha value="1.0"/>
            </ColorStop>
          </ColorLine>
          <x0 value="342"/>
          <y0 value="348"/>
          <x1 value="342"/>
          <y1 value="-231"/>
          <x2 value="-237"/>
          <y2 value="348"/>
        </Paint>
        <Glyph value="glyph00003"/>
      </Paint>
      <Paint index="1" Format="12"><!-- PaintTransform -->
        <Paint Format="10"><!-- PaintGlyph -->
          <Paint Format="4"><!-- PaintLinearGradient -->
            <ColorLine>
              <Extend value="pad"/>
              <!-- StopCount=2 -->
              <ColorStop index="0">
                <StopOffset value="0.0"/>
                <PaletteIndex value="1"/>
                <Alpha value="1.0"/>
              </ColorStop>
              <ColorStop index="1">
                <StopOffset value="1.0"/>
                <PaletteIndex value="0"/>
                <Alpha value="1.0"/>
              </ColorStop>
            </ColorLine>
            <x0 value="933"/>
            <y0 value="348"/>
            <x1 value="933"/>
            <y1 value="-231"/>
            <x2 value="354"/>
            <y2 value="348"/>
          </Paint>
          <Glyph value="glyph00003"/>
        </Paint>
        <Transform>
          <xx value="-1.0"/>
          <yx value="0.0"/>
          <xy value="0.0"/>
          <yy value="1.0"/>
          <dx value="1275.0"/>
          <dy value="0.0"/>
        </Transform>
      </Paint>
    </LayerList>
    <ClipList Format="1">
      <Clip>
        <Glyph value="u1F3AA"/>
        <ClipBox Format="1">
          <xMin value="220"/>
          <yMin value="-220"/>
          <xMax value="800"/>
          <yMax value="360"/>
        </ClipBox>
      </Clip>
    </ClipList>
  </COLR>
```

**Comment by drott** [comment]
The `ColorLine` coordinates and transform seem to be okay. This issue might have something to do with Skia clipping the layer. Needs more investigation. If I change the TTX to use a smaller value than 1275 for `dx`, then I can still see parts of the gate

**Comment by drott** [comment]
In this particular simplified tent case, the ClipBox computed is too small:

```
        <ClipBox Format="1">
          <xMin value="220"/>
          <yMin value="-220"/>
          <xMax value="800"/>
          <yMax value="360"/>
        </ClipBox>
```

The right half of the tent entrance extens past ~1100, an x max value of 800 is too small.

**Comment by anthrotype** [comment]
Hm I'm not able to reproduce using nanoemoji main branch (tagged v0.9.4). If I run `nanoemoji --gen_svg_font_diffs /tmp/emoji_u1f3aa.svg` using the simplified circus tent SVG provided above, I get the following (correct?) result:

![image](https://user-images.githubusercontent.com/6939968/133589520-153a8431-5080-49f4-9b11-5dea5e6d7e5d.png)

**Comment by anthrotype** [comment]
the result doesn't change (at least visually) if I do the same using the branch from #339 (only the linear gradient coordinates get shifted but the rendering is the same as above)

**Comment by drott** [comment]
![tent_fixed](https://user-images.githubusercontent.com/1021784/133596139-d927c57e-0e86-435c-9150-a7b07ca19629.png)

Previously, the original breakage I saw was the above. However, that one is fixed with #339 applied as well. So perhaps something went wrong with the reduction. I can't reproduce the clipping either here anymore :(. The full glyph, non reduced, has an ok ClipBox:

```
     <ClipBox Format="1">
          <xMin value="60"/>
          <yMin value="-220"/>
          <xMax value="1200"/>
          <yMax value="920"/>
        </ClipBox>
```

So I think we can consider this fixed.

**Comment by anthrotype** [comment]
> I can't reproduce the clipping either here anymore :(

Actually, I am seeing different handling of ClipBoxes between the `colr_test` executable and Google Chrome Canary.app.

In the former, it appears that the nominal ClipBox values are completely ignored; i.e. if ClipBox is forced to be narrower than the actual glyph extents, no clipping actually occurs:

```diff
--- /dev/fd/63  2021-09-20 14:42:51.000000000 +0200
+++ /dev/fd/62  2021-09-20 14:42:51.000000000 +0200
@@ -290,7 +290,7 @@
         <ClipBox Format="1">
           <xMin value="60"/>
           <yMin value="-220"/>
-          <xMax value="1200"/>
+          <xMax value="600"/>
           <yMax value="920"/>
         </ClipBox>
       </Clip>
```

```
$ colr_test --font Font_1.ttf --output skia_png/emoji_u26ab.png --text ⚫ --height 256 --width 256
```

![emoji_u26ab](https://user-images.githubusercontent.com/6939968/134004417-1878c900-1638-42fa-957f-29504a0d808c.png)

Whereas in the latter, I can seen clippings after I hack the font to make a ClipBox narrower.

![image](https://user-images.githubusercontent.com/6939968/134004056-a6e0c501-26ab-4ede-9dbb-338b8a33a726.png)

The test font (containing only one color glyph uni26AB) can be found here: [colr-clipbox-test.zip](https://github.com/googlefonts/nanoemoji/files/7195745/colr-clipbox-test.zip)

**Comment by anthrotype** [comment]
If I modify the skia's `DEPS` file like this, by having it fetch freetype2 submodule at commit 529158983ddde23ac422fc28939b0eb2bbaa04a1, and then do `tools/git-sync-deps` and finally rebuild the `colr_test` utility, I can then see clipbox being clipped correctly (just like in Chrome Canary).

```diff
diff --git a/DEPS b/DEPS
index 57d202efbe..b4c2bc39b3 100644
--- a/DEPS
+++ b/DEPS
@@ -23,7 +23,7 @@ deps = {
   "third_party/externals/dng_sdk"         : "https://android.googlesource.com/platform/external/dng_sdk.git@c8d0c9b1d16bfda56f15165d39e0ffa360a11123",
   "third_party/externals/egl-registry"    : "https://skia.googlesource.com/external/github.com/KhronosGroup/EGL-Registry@a0bca08de07c7d7651047bedc0b653cfaaa4f2ae",
   "third_party/externals/expat"           : "https://chromium.googlesource.com/external/github.com/libexpat/libexpat.git@a28238bdeebc087071777001245df1876a11f5ee",
-  "third_party/externals/freetype"        : "https://chromium.googlesource.com/chromium/src/third_party/freetype2.git@fed5521016227bf8cc4475f66450a9963568d162",
+  "third_party/externals/freetype"        : "https://chromium.googlesource.com/chromium/src/third_party/freetype2.git@529158983ddde23ac422fc28939b0eb2bbaa04a1",
   "third_party/externals/harfbuzz"        : "https://chromium.googlesource.com/external/github.com/harfbuzz/harfbuzz.git@368e9578873798e2d17ed78a0474dec7d4e9d6c0",
   "third_party/externals/icu"             : "https://chromium.googlesource.com/chromium/deps/icu.git@a0718d4f121727e30b8d52c7a189ebf5ab52421f",
   "third_party/externals/imgui"           : "https://skia.googlesource.com/external/github.com/ocornut/imgui.git@9418dcb69355558f70de260483424412c5ca2fce",
```

@drott said he'll "make a fix for Skia to update the FreeType commit in the DEPS file". Meanwile, I will continue trying to repro this issue with clipbox too small.

**Comment by drott** [comment]
> So I think we can consider this fixed.

Looks like the problem was that ClipBox was not applied in Skia colr_test with an FT version that did not have the ClipBox format 1 => 0 compatibility change, and applying 529158983ddde23ac422fc28939b0eb2bbaa04a1 does expose the small ClipBoxes.

**Comment by anthrotype** [comment]
I can repro now

![image](https://user-images.githubusercontent.com/6939968/134013388-b83576e5-083d-4f66-978f-330f6cd69c0a.png)

**Comment by anthrotype** [comment]
ok, I found where the issue is. When traversing the paint graph and unioning the bounding boxes of the various PaintGlyphs, when a reflection is found (e.g. negtive xx or yy whereby coordinates get flipped along the axes), the code was not normalizing the transformed bounding rectangle by turning it the right way up i.e. such that xMin <= xMax and yMin <= yMax
FontTools arrayTools module has a normRect function that does just that. After using it, I get correct bounding boxes and no more unwanted clipping. I'll make a PR now
