### ISSUE TITLE
[OT-SVG] picosvg shape reuse not working when reused paths have different fill  

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/nanoemoji#337]
Take this simple SVG containing three rects of different colors:

```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <rect fill="yellow" x="40" y="10" width="20" height="20"/>
  <rect fill="red" x="40" y="40" width="20" height="20" />
  <rect fill="blue" x="40" y="70" width="20" height="20" />
</svg>
```
![image](https://user-images.githubusercontent.com/6939968/133472167-bd9a2b54-83d7-40ee-ae67-5b9b513259df.png)

When compiling an OT-SVG font from it with the command `nanoemoji --color_format=picosvg --pretty_print /tmp/e002.svg`, the resulting `SVG  ` table contains the following:

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
  <g id="glyph2" transform="matrix(12 0 0 12 37.5 -950)">
    <path d="M40,10 L60,10 L60,30 L40,30 L40,10 Z" fill="yellow" id="e002.0"/>
    <use xlink:href="#e002.0" y="30" fill="red"/>
    <use xlink:href="#e002.0" y="60" fill="blue"/>
  </g>
</svg>
```

All three rects render yellow, using the same fill as the first element from which they inherit the path.d.
![image](https://user-images.githubusercontent.com/6939968/133472297-505c297a-c031-4b6d-bf95-77db08cd0ac9.png)

The `fill` attribute on the `<use>` element is ignored because the referenced path already contains a `fill`, so the attribute does not "cascade" down, the reused path's fill takes priority over the `fill` defined onto the `<use>` element that references it.
Basically attributes on `<use>` do not override those explicitly defined on the referenced element, they can only be inherited when the latter doesn't define them.

We could fix this by moving the reused path (without its fill, only with the `d` attribute) to the `<defs>` and replace all occurences (including the first one) with `<use>` elements that each define their own distinct `fill`, e.g.:

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
  <defs>
    <path d="M40,10 L60,10 L60,30 L40,30 L40,10 Z" id="e002.0"/>
  </defs>
  <g id="glyph2" transform="matrix(12 0 0 12 37.5 -950)">
    <use xlink:href="#e002.0" fill="yellow"/>
    <use xlink:href="#e002.0" y="30" fill="red"/>
    <use xlink:href="#e002.0" y="60" fill="blue"/>
  </g>
</svg>
```

However, doing so inconditionally, even when the fills between the reused shapes are actually the same would be inefficient because we repeat the same fill more than once, on each distinct `<use>`.
A smarter shape reuse should identify both these situations (reuse of shape only with distinct fills, and reuse of both shape and fill) and do the right thing, but the code is already complicated and I'm tempted to do the dumb (but correct) thing first (only reuse shape, never reuse fill whether or not it's the same), and add a TODO for later.

**Comment by rsheeter** [comment]
> only reuse shape, never reuse fill whether or not it's the same

+1, my bad for not considering that use fill would only work on something that didn't have one
