### ISSUE TITLE
use headless browsers  to generate raster diffs of input SVGs vs compiled fonts

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/nanoemoji#338]
Currently the `--gen_svg_font_diffs` uses a [custom executable that links to skia](https://github.com/rsheeter/skia_colr) and converts a font file and string of emoji text to a raster image, which we compare against a PNG of the original input SVG as rasterised by resvg library, and image-diffed using Pillow.
Given that both [Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) and [Firefox](https://hacks.mozilla.org/2017/12/using-headless-mode-in-firefox/) support generating screenshots in headless mode, we could maybe use that to generate the rasters for both the input SVG and the corresponding color glyph from the compiled vector color font.
This would work not only for COLRv1 (via Chrome Canary), but also for OT-SVG (via FireFox).
And we would test _the actual thing_.

**Comment by M-a-c** [comment]
This is a good idea.  _someone may be using chrome for something like that 😉 _


here is a script to help out a little bit at least

```python

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.utils import ChromeType
from requests.utils import quote
import os

def f():
    self.chrome_options = webdriver.ChromeOptions()
    self.chrome_options.add_argument('--headless')
    self.chrome_options.add_argument('--no-sandbox')
    self.chrome_options.add_argument('--disable-gpu')
    self.chrome_options.add_argument(f'--window-size={width}x{height}')
    self.chrome_options.add_argument('--hide-scrollbars')
    
    self.driver = webdriver.Chrome(ChromeDriverManager().install(), chrome_options=self.chrome_options)
    
    cwd = os.getcwd()
    cwdsafe = quote(os.getcwd(), safe='/')

    #could loop here
    self.driver.get(f'file://{cwdsafe}/{Svg_File_String}')
    self.driver.save_screenshot(f'{cwd}/{Png_File_String}')

    self.driver.quit()
```

**Comment by rsheeter** [comment]
Now that Chrome has COLRv1 we could use the browser for svg2png **and** font2png, thus diffing browser output for original svg vs for COLRv1 font of the same.

**Comment by rsheeter** [comment]
I seem to be hitting a problem where neither directly spawning Chrome nor using selenium loads fonts. The page I want to screenshot looks something like this:

```html
<!DOCTYPE html>
<style>
    @font-face {
        font-family: "TestFont";
        src: url(./Font.ttf);
    }
    * {
        margin: 0;
        overflow: hidden;
        font-family: "TestFont";
    }
</style>
<span id="glyph" style="font-size: 8em;">&#x270d;</span>
```

My local copy of the 270d svg is hacked to have a red pen instead of blue. Screenshots consistently show the blue pen. If I load the page in an actual browser instance I see the red pen. I see comments online about using things like `--virtual-time-budget` to await fonts but so far I have failed to find the correct magic incantation.

**Comment by drott** [comment]
When do you take the screenshots? Can you wait for the `document.fonts.ready()` promise before taking the snapshot?

**Comment by rsheeter** [comment]
In the light of a new day I have realized pebkac. My default Chrome is 97 so passing `--enable-features=COLRV1Fonts` helps considerably :D
