### ISSUE TITLE
Add an otsvg to colrv1 converter

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/nanoemoji#363]
Potential test fonts, in addition to our own:

1. https://www.colorfonts.wtf/#section5, Bungee at least is open

**Comment by Theelx** [comment]
I don't know much about fonts, but if there's a theoretical way to convert OT-SVG fonts to COLRv1, I'd absolutely help with that. I'm currently using the Pride font from https://www.colorfonts.wtf/#section5 on a website, and it's super annoying that the colors won't show up on Chrome. If there's anything I can do to help build a converter, I'd love to try!

**Comment by rsheeter** [comment]
It's plausible - nanoemoji's purpose is to compile {svgs} => colrv1 - but I would need to pause to think about the best way to approach it. Svg supports bitmaps and COLRv1 does not (https://github.com/googlefonts/colr-gradients-spec/issues/272) so some things you can do in SVG cannot be done in COLRv1.

**Comment by Theelx** [comment]
Would it be reasonable to only support converting vector SVG fonts to COLRv1, or would any such conversion feature have to support bitmap SVG fonts too?

**Comment by rsheeter** [comment]
It's reasonable and I suspect we will need to do it.

**Comment by rsheeter** [comment]
https://github.com/googlefonts/nanoemoji/pull/390 has some exploratory hacking toward adding COLRv1 to ot-svg fonts.

**Comment by anthrotype** [comment]
`svg2colr` branch was merged so I think this can be closed

**Comment by rsheeter** [comment]
Good catch, closing as fixed by #390. If there are bugs we can file issues for them individually.
