### ISSUE TITLE
Color variants sometimes make firefox sad?

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/nanoemoji#368]
https://github.com/googlefonts/noto-emoji/tree/colr_and_svg_test/colrv1 has a set of test fonts experimenting with building a font that works in Chrome, FireFox, and hopefully Safari. It uses the handwriting emoji, with the pen recolored red so it's easy to tell if it works. For example, after building (`for f in *.toml; do rm -rf build/picosvg; nanoemoji $f; done` to avoid #367), load [handwriting.html](https://github.com/googlefonts/noto-emoji/blob/colr_and_svg_test/colrv1/handwriting.html).

In these examples:

* row 1 font has COLRv1 *and* SVG
* row2 is COLRv1 only; the expected behavior is to draw the blank fallback glyph, which seems to be whats happening for the leftmost (single codepoint) instance only
* row3 is glyf, which again somehow only works on the leftmost instance

Chrome renders as expected:
![image](https://user-images.githubusercontent.com/6466432/149455687-1e59e9bc-378a-47be-b9f8-d76ea255dded.png)

On Firefox for the base 270d we see COLRv1 fallback to blank (expected) and the glyf-only font render but for all the skin tone variants it just falls back to the system font (CBDT Noto in my case):
![image](https://user-images.githubusercontent.com/6466432/149455907-de421fc5-2488-494e-a1b9-cf52e66be69c.png)

On Mac ... we shall see, I don't have one on me :)

The leftmost emoji is a single codepoint `270d`, the rest all have fitzpatrick modifiers. So for some reason firefox elects system fallback as soon as we add the fitzpatrick modifier for the COLRv1 and glyf fonts, but not the COLRv1+ot-svg one.

**Comment by rsheeter** [comment]
@behdad proposed in IM there may be validation in FF at play, something along the lines of a sequence with a fitzpatrick modifier *must* be colorful so reject a font that cannot provide a colored result. That would explain naked `270d`, the leftmost emoji, working and the rest - all fitzpatrick modifier sequences - being rejected in rows 2 and 3. In row 1 SVG is deemed colorful and accepted.

https://searchfox.org/mozilla-central/source/gfx/thebes/gfxTextRun.cpp#3075

**Comment by behdad** [comment]
Specifically:
https://searchfox.org/mozilla-central/source/gfx/thebes/gfxTextRun.cpp#3063-3071

**Comment by rsheeter** [comment]
Amazing, thank you. I was coming up blank on why this would occur. I think entirely WAI, nothing to fix here.
