### ISSUE TITLE
maximum_color is unhappy with > 1 palette

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/nanoemoji#421]
In a clone of google/fonts:

```
maximum_color ofl/reemkufiink/ReemKufiInk-Regular.ttf

nanoemoji/colr_to_svg.py", line 410, in colr_to_svg
    assert len(ttfont["CPAL"].palettes) == 1, "We assume one palette"
AssertionError: We assume one palette
```

This is far less helpful than building a functional font with only one - presumably the first - palette.

**Comment by anthrotype** [comment]
hm no good.

(LOL how the line just above that says `"""For testing only, don't use for real!"""`)

To fully support this we need https://github.com/googlefonts/nanoemoji/issues/422

> building a functional font with only one - presumably the first - palette.

**Comment by anthrotype** [comment]
> building a functional font with only one - presumably the first - palette.

That's trivial, we can maybe do that as first round

**Comment by rsheeter** [comment]
I like the idea of doing the trivial fix first :)

**Comment by anthrotype** [comment]
if I apply the following patch, I can get past that assertion and the subsequent code will use `font["CPAL"].palettes[0]`

```diff
diff --git a/src/nanoemoji/colr_to_svg.py b/src/nanoemoji/colr_to_svg.py
index 9c514e9..4778558 100644
--- a/src/nanoemoji/colr_to_svg.py
+++ b/src/nanoemoji/colr_to_svg.py
@@ -407,7 +407,13 @@ def colr_to_svg(
     rounding_ndigits: Optional[int] = None,
 ) -> Dict[str, SVG]:
     """For testing only, don't use for real!"""
-    assert len(ttfont["CPAL"].palettes) == 1, "We assume one palette"
+    num_palettes = len(ttfont["CPAL"].palettes)
+    if num_palettes > 1:
+        logging.warning(
+            "Multiple CPAL palettes are not supported! Only using the first"
+        )
+    elif num_palettes < 1:
+        raise ValueError("No CPAL palettes found, at least one required")

     colr_version = ttfont["COLR"].version
     if colr_version == 0:
```

But... then I hit a new assertion error because some glyphs have zero advance width (which is normal and expected for glyphs used as combining marks).

```
W0729 15:25:50.514565 4340401536 colr_to_svg.py:412] Multiple CPAL palettes are not supported! Only using the first
Traceback (most recent call last):
...
  File "/Users/clupo/Github/nanoemoji/src/nanoemoji/colr_to_svg.py", line 329, in _view_box_and_transform
    view_box = view_box_callback(glyph_name)
  File "/Users/clupo/Github/nanoemoji/src/nanoemoji/generate_svgs_from_colr.py", line 56, in <lambda>
    for glyph_name, svg in colr_to_svg(lambda gn: _view_box(font, gn), font).items():
  File "/Users/clupo/Github/nanoemoji/src/nanoemoji/generate_svgs_from_colr.py", line 41, in _view_box
    assert region.w > 0, f"0-width region for {glyph_name}"
AssertionError: 0-width region for behDotless-ar.init.Hah
```

I forgot why we do that, but we should support converting glyphs with 0 advance somehow

**Comment by anthrotype** [comment]
if I comment-out all three of those `assert`s, I can run `maximum_color` tool on ReemKufiInk-Regular.ttf without crashing.

Now, I'll see whether the 0-width glyphs display correctly, and most importantly _why_ those assertions are there in the first place.

**Comment by anthrotype** [comment]
hm, it looks like we had removed a similar assertion about width==0 in https://github.com/googlefonts/nanoemoji/pull/412

in that conversation, it appeared these asserts have something to do with bitmap conversion..

>> Is it because when width is 0, a bitmap CBDT glyph would otherwise completely disappear

> I think this was true but iirc should no longer be. In any case, definitely a bad assert, good catch.

**Comment by anthrotype** [comment]
Would be nice to summon @khaledhosny to confirm that we haven't crippled his Arabic font.
If I understand correctly, one way to activate that "behDotless-ar.init.Hah" glyph (which has 0 advance width) is to write a text like this "ٮح"

 ‎066E ARABIC LETTER DOTLESS BEH
 ‎062D ARABIC LETTER HAH

$ hb-shape /tmp/reemkufiink/Font.ttf --unicodes=066E,062D
[gid83=1+515|gid43=0@80,0+80]

This is how the COLRv1 looks in Chrome 103 on macOS: 

<img width="208" alt="Screen Shot 2022-07-29 at 16 35 10" src="https://user-images.githubusercontent.com/6939968/181783344-9b94db36-9efd-40a1-9b74-64dc50015c1e.png">

And the OT-SVG font (as converted by maximum_color tool after removing the above-mentioned assertions) appears in FireFox 102 (Safari 15.5 also using OT-SVG table appears the same as FireFox)

<img width="201" alt="Screen Shot 2022-07-29 at 16 46 21" src="https://user-images.githubusercontent.com/6939968/181785486-9797bfde-c536-47f6-9073-03d291a98044.png">


I don't know Arabic, so I can't tell which one is the correct one (even though "visually" the second one [FireFox & Safari's] looks better to me as the letter shapes don't overlap but again I'm not arabic expert)

**Comment by khaledhosny** [comment]
The COLRv1 rendering is the correct one, the two glyphs should be attached. The font does not use cursive anchors to attach the two glyphs, but relied on the `behDotless-ar.init.Hah` having a -ve left side bearing.

**Comment by anthrotype** [comment]
The first one (COLRv1 on Chrome) seems to be the correct rendering, because I tried to render the same string with the black-and-white ReemKufi.otf and all three browsers agree on this:

<img width="209" alt="Screen Shot 2022-07-29 at 16 51 43" src="https://user-images.githubusercontent.com/6939968/181786516-23585a64-4b09-4547-8900-dcbad83bdfb3.png">

Therefore something must have gone wrong in the COLR=>OT-SVG conversion

**Comment by anthrotype** [comment]
@khaledhosny thanks for confirming!

**Comment by anthrotype** [comment]
Ha! After commenting out another couple of lines I can make the ReemKufiInk OT-SVG work with the 0-width glyphs: 

```diff
diff --git a/src/nanoemoji/colr_to_svg.py b/src/nanoemoji/colr_to_svg.py
index 9c514e9..903fe9c 100644
--- a/src/nanoemoji/colr_to_svg.py
+++ b/src/nanoemoji/colr_to_svg.py
@@ -312,8 +312,8 @@ def glyph_region(ttfont: ttLib.TTFont, glyph_name: str) -> Rect:

     map_font_space_to_viewbox handles font +y goes up => svg +y goes down."""
     width = ttfont["hmtx"][glyph_name][0]
-    if width == 0:
-        width = ttfont["glyf"][glyph_name].xMax
+    # if width == 0:
+    #     width = ttfont["glyf"][glyph_name].xMax
     return Rect(
         0,
         -ttfont["OS/2"].sTypoAscender,
```

it now looks correct both in FireFox and Safari (the latter shown below)

<img width="209" alt="Screen Shot 2022-07-29 at 16 51 43" src="https://user-images.githubusercontent.com/6939968/181789429-e8154db6-960e-4279-97dd-4e973cba7d3e.png">

I think all these hacks were put in place in order to be able to not chop off CBDT glyphs when we rasterize SVG=>PNG (this bug basically https://github.com/googlefonts/nanoemoji/issues/402)

We should either get rid of them of put them behind a flag somehow

**Comment by anthrotype** [comment]
attempting to `maximum_color "CairoPlay[slnt,wght].ttf"` fails with

```
  File "/Users/clupo/Github/nanoemoji/src/nanoemoji/generate_svgs_from_colr.py", line 40, in _view_box
    region = glyph_region(font, glyph_name)
  File "/Users/clupo/Github/nanoemoji/src/nanoemoji/colr_to_svg.py", line 316, in glyph_region
    width = ttfont["glyf"][glyph_name].xMax
AttributeError: 'Glyph' object has no attribute 'xMax'
```

Yet one more reason to get rid of those lines.

The error is probably because the glyph is not only 0-width but also has 0 contours (it's a whitespace glyph), so has no bounding box attributes
