### ISSUE TITLE
Generate PNG's

### ISSUE THREAD

**Issue by JeppeKlitgaard** [googlefonts/nanoemoji#440]
I was wondering if it is possible to generate a directory of PNG's using `nanoemoji`. It seems like all the requisite parts needed to make it work are in place already.

Is this already possible? If not, is it within the scope of the project to include that? I think many emoji-fonts like to export their emojis as PNG's in addition to shipping them as a color font.

**Comment by JeppeKlitgaard** [comment]
Ah, brilliant! Thank you so much!

**Comment by rsheeter** [comment]
I think that means nothing to do here, plz reopen if that's not the case
